services:
  evolution-api:
    image: atendai/evolution-api:v1.8.2
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=https://assets-dean-registered-issue.trycloudflare.com
      - DOCKER_ENV=true
      - LOG_LEVEL=DEBUG,INFO,ERROR,WARN
      - LOG_COLOR=true
      - LOG_BAILEYS=error
      - NODE_ENV=production
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=ADMIN_GLOBAL_KEY_INMOCMS_123
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:postgres@postgres:5432/evolution
      - DATABASE_CONNECTION_CLIENT_NAME=evolution
      # Configuración de CACHE (Vital para velocidad)
      - CACHE_REDIS_ENABLED=false
      - CACHE_REDIS_URI=redis://redis:6379/0
      - CACHE_REDIS_PREFIX=evolution
      # Optimization
      - DATABASE_SAVE_DATA_INSTANCE=false
      - DATABASE_SAVE_DATA_NEW_MESSAGE=false
      - DATABASE_SAVE_MESSAGE_UPDATE=false
      - DATABASE_SAVE_DATA_CONTACTS=false
      - DATABASE_SAVE_DATA_CHATS=false
      - DATABASE_SAVE_DATA_LABELS=false
      - DATABASE_SAVE_DATA_HISTORIC=false
      - WEBHOOK_GLOBAL_ENABLED=false
    deploy:
      resources:
        limits:
          memory: 2G
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: evolution_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=evolution
    ports:
      - "5433:5432"
    volumes:
      - evolution_db_data:/var/lib/postgresql/data
    command: postgres -c max_connections=50 -c shared_buffers=64MB -c work_mem=4MB
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:7-alpine
    container_name: evolution_redis
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: always
    command: tunnel --no-autoupdate --url http://evolution-api:8080
    depends_on:
      - evolution-api

volumes:
  evolution_db_data:
