// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[tenant_slug]" | "/[tenant_slug]/propiedad/[id]" | "/[tenant_slug]/propiedades/[id]" | "/admin" | "/agentes" | "/ajustes" | "/clientes" | "/cuenta/perfil" | "/cuenta/plan" | "/cuenta/plan/checkout" | "/cuenta/plan/success" | "/dashboard" | "/demo-expired" | "/documentos" | "/documentos/[id]" | "/documentos/nuevo" | "/invitacion/[token]" | "/leads" | "/leads/[id]" | "/leads/[id]/editar" | "/leads/captacion" | "/leads/nuevo" | "/login" | "/marketing" | "/marketing/ai-studio" | "/marketing/automatizaciones" | "/marketing/automatizaciones/nueva" | "/marketing/campanas" | "/marketing/campanas/nueva" | "/marketing/canales" | "/marketing/portales" | "/marketing/portales/config/[portalName]" | "/mensajes" | "/pipeline" | "/portal" | "/propiedades" | "/propiedades/[id]" | "/propiedades/[id]/editar" | "/propiedades/[id]/reporte" | "/propiedades/compartidas" | "/propiedades/importar" | "/propiedades/nuevo" | "/recuperar" | "/reset-password" | "/signup" | "/tareas" | "/visitas"
type AppRouteHandlerRoutes = "/api/webhooks/mercadopago"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[tenant_slug]": { "tenant_slug": string; }
  "/[tenant_slug]/propiedad/[id]": { "tenant_slug": string; "id": string; }
  "/[tenant_slug]/propiedades/[id]": { "tenant_slug": string; "id": string; }
  "/admin": {}
  "/agentes": {}
  "/ajustes": {}
  "/api/webhooks/mercadopago": {}
  "/clientes": {}
  "/cuenta/perfil": {}
  "/cuenta/plan": {}
  "/cuenta/plan/checkout": {}
  "/cuenta/plan/success": {}
  "/dashboard": {}
  "/demo-expired": {}
  "/documentos": {}
  "/documentos/[id]": { "id": string; }
  "/documentos/nuevo": {}
  "/invitacion/[token]": { "token": string; }
  "/leads": {}
  "/leads/[id]": { "id": string; }
  "/leads/[id]/editar": { "id": string; }
  "/leads/captacion": {}
  "/leads/nuevo": {}
  "/login": {}
  "/marketing": {}
  "/marketing/ai-studio": {}
  "/marketing/automatizaciones": {}
  "/marketing/automatizaciones/nueva": {}
  "/marketing/campanas": {}
  "/marketing/campanas/nueva": {}
  "/marketing/canales": {}
  "/marketing/portales": {}
  "/marketing/portales/config/[portalName]": { "portalName": string; }
  "/mensajes": {}
  "/pipeline": {}
  "/portal": {}
  "/propiedades": {}
  "/propiedades/[id]": { "id": string; }
  "/propiedades/[id]/editar": { "id": string; }
  "/propiedades/[id]/reporte": { "id": string; }
  "/propiedades/compartidas": {}
  "/propiedades/importar": {}
  "/propiedades/nuevo": {}
  "/recuperar": {}
  "/reset-password": {}
  "/signup": {}
  "/tareas": {}
  "/visitas": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
