// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(auth)/invitacion/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invitacion/[token]">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/invitacion/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/recuperar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recuperar">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/recuperar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/agentes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agentes">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/agentes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/ajustes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ajustes">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/ajustes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clientes">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/cuenta/perfil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cuenta/perfil">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/cuenta/perfil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/cuenta/plan/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cuenta/plan/checkout">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/cuenta/plan/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/cuenta/plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cuenta/plan">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/cuenta/plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/cuenta/plan/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cuenta/plan/success">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/cuenta/plan/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/documentos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documentos/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/documentos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/documentos/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documentos/nuevo">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/documentos/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/documentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documentos">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/documentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/leads/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads/[id]/editar">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/leads/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/leads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/leads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/leads/captacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads/captacion">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/leads/captacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/leads/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads/nuevo">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/leads/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/marketing/ai-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing/ai-studio">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/marketing/ai-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/marketing/automatizaciones/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing/automatizaciones/nueva">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/marketing/automatizaciones/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/marketing/automatizaciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing/automatizaciones">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/marketing/automatizaciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/marketing/campanas/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing/campanas/nueva">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/marketing/campanas/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/marketing/campanas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing/campanas">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/marketing/campanas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/marketing/canales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing/canales">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/marketing/canales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/marketing/portales/config/[portalName]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing/portales/config/[portalName]">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/marketing/portales/config/[portalName]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/marketing/portales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing/portales">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/marketing/portales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/mensajes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mensajes">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/mensajes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/propiedades/[id]/editar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/propiedades/[id]/editar">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/propiedades/[id]/editar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/propiedades/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/propiedades/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/propiedades/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/propiedades/[id]/reporte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/propiedades/[id]/reporte">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/propiedades/[id]/reporte/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/propiedades/compartidas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/propiedades/compartidas">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/propiedades/compartidas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/propiedades/importar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/propiedades/importar">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/propiedades/importar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/propiedades/nuevo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/propiedades/nuevo">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/propiedades/nuevo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/propiedades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/propiedades">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/propiedades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/tareas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tareas">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/tareas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/visitas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/visitas">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/visitas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(public)/[tenant_slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[tenant_slug]">> = Specific
  const handler = {} as typeof import("../../../app/(public)/[tenant_slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(public)/[tenant_slug]/propiedad/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[tenant_slug]/propiedad/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(public)/[tenant_slug]/propiedad/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(public)/[tenant_slug]/propiedades/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[tenant_slug]/propiedades/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(public)/[tenant_slug]/propiedades/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(public)/portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal">> = Specific
  const handler = {} as typeof import("../../../app/(public)/portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/demo-expired/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo-expired">> = Specific
  const handler = {} as typeof import("../../../app/demo-expired/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhooks/mercadopago/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/mercadopago">> = Specific
  const handler = {} as typeof import("../../../app/api/webhooks/mercadopago/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
